[[entry]]
played_at = "2026-08-21T03:30:45Z"
path = "http://192.168.4.28:32400/library/parts/4458/1765530894/file.flac?X-Plex-Token=jWPQrk2d8QwwsM5E6XGx"
title = "Lust"
artist = "SAINt JHN"
album = "Collection One"
track_number = 1
duration_secs = 166
